### ISSUE TITLE
Segfault during `run --wait` when reading manifest from stdin/file

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#929]
**What steps did you take and what happened:**
A segfault occurs when the output from `sonobuoy gen` is passed via file or stdin to `sonobuoy run`.

```
./sonobuoy gen --mode quick | ./sonobuoy run --wait -f -                                                                                                                                                                              0|1 ↵  7513  15:19:59
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=sonobuoy resource=services
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x10a7e5e]

goroutine 1 [running]:
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).RunManifest.func1(0xc0007e9a18, 0xc0007e99c8, 0x2)
	/go/src/github.com/vmware-tanzu/sonobuoy/pkg/client/run.go:104 +0x3e
github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0003dca40, 0xc0007e9c48, 0xc000628420, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:405 +0x155
github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc0003dca40, 0xc0007e9c48, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:293 +0x9f
github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait.Poll(0x4a817c800, 0x4e94914f0000, 0xc0007e9c48, 0x7, 0xffffffffffffffff)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:287 +0x4d
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).RunManifest(0xc000029e00, 0xc000456180, 0xc000314000, 0x11c2, 0x1e00, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/sonobuoy/pkg/client/run.go:130 +0x791
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).Run(0xc000029e00, 0xc000456180, 0x23433e0, 0x0)
	/go/src/github.com/vmware-tanzu/sonobuoy/pkg/client/run.go:163 +0x99
github.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.submitSonobuoyRun(0xc000139b80, 0xc00002e900, 0x0, 0x3)
	/go/src/github.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app/run.go:109 +0x1d5
github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc000139b80, 0xc00002e870, 0x3, 0x3, 0xc000139b80, 0xc00002e870)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000de000, 0x0, 0x1364c80, 0xc0000ae058)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/vmware-tanzu/sonobuoy/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/go/src/github.com/vmware-tanzu/sonobuoy/main.go:26 +0x27

```

This is happening because the wait logic tries to get the status of the aggregator pod using the [`config.Config.Namespace`](https://github.com/vmware-tanzu/sonobuoy/blob/master/pkg/client/run.go#L104). This config is only set in the case where we aren't using a file: https://github.com/vmware-tanzu/sonobuoy/blob/master/cmd/sonobuoy/app/run.go#L68.

**What did you expect to happen:**
For the run to complete successfully with no segfault.

**Environment:**
- Sonobuoy version: Sonobuoy Version: v0.16.1-2-g3290552

**Comment by zubron** [comment]
I encountered this working on some tests. I've got a fix for it which I'll make a PR for and will adapt one of the tests I was writing for this issue.
